apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami-deployment
  labels:
    app: whoami
spec:
  selector:
    matchLabels:
      app: whoami-app
  template:
    metadata:
      labels:
        app: whoami-app
    spec:
      containers:
        - name: whoami-container
          image: traefik/whoami
          ports:
            - containerPort: {{ .Values.port }}
          env:
            - name: "OWNER"
              value: {{ .Values.owner }}
            - name: "TEST_VERSION"
              value: {{ .Values.version }}
            - name: "WHOAMI_PORT_NUMBER"
              value: {{ .Values.port | quote }}

---
apiVersion: v1
kind: Service
metadata:
  name: whoami-service
spec:
  selector:
    app: whoami-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.port }}
  type: ClusterIP